### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by DamianMorozov** [juba0x00/Rummage#1]
I have to try use it, but got an error.
```
Enter Your Search Key: test@gmail.com
2022-05-28 xx:xx:xx
Traceback (most recent call last):
  File "...\cli.py", line 31, in <module>
    Finder.Search(SearchKey)
  File "...\modules\search.py", line 52, in Search
    self.__SingleSearch(SearchKey)
  File "...\modules\search.py", line 68, in __SingleSearch
    if self.DatabaseFinder.HistorySearch():
  File "...\database.py", line 47, in HistorySearch
    self.__cursor.execute("SELECT * FROM History WHERE SearchKey ='{}'".format(LeaksFinder.GetSearchKey()))
sqlite3.OperationalError: no such table: History
```

**Comment by juba0x00** [comment]
@DamianMorozov
We are very sorry for this late response, I have fixed the issue.
just clone the repository and run `install_requirements.sh` to set up everything.
the program will start tor automatically, no need for starting it by yourself
